### ISSUE TITLE
Implement slog::Serialize for std::net::SocketAddr

### ISSUE THREAD

**Issue by imp** [slog-rs/slog#109]
Right now it doesn't work out of the box, but it surely can be quite handy for network applications
```
error[E0277]: the trait bound `for<'c, 'd> std::net::SocketAddr: std::ops::Fn<(&'c slog::Record<'d>,)>` is not satisfied
  --> src/main.rs:54:9
   |
54 |         info!(server_log, "Listening on"; "socket" => active.socket);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'c, 'd> std::ops::Fn<(&'c slog::Record<'d>,)>` is not implemented for `std::net::SocketAddr`
   |
   = note: required because of the requirements on the impl of `slog::Serialize` for `std::net::SocketAddr`
   = note: required for the cast to the object type `slog::Serialize`
   = note: this error originates in a macro outside of the current crate

error[E0277]: the trait bound `for<'c, 'd> std::net::SocketAddr: std::ops::FnOnce<(&'c slog::Record<'d>,)>` is not satisfied
  --> src/main.rs:54:9
   |
54 |         info!(server_log, "Listening on"; "socket" => active.socket);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'c, 'd> std::ops::FnOnce<(&'c slog::Record<'d>,)>` is not implemented for `std::net::SocketAddr`
   |
   = note: required because of the requirements on the impl of `slog::Serialize` for `std::net::SocketAddr`
   = note: required for the cast to the object type `slog::Serialize`
   = note: this error originates in a macro outside of the current crate

error: aborting due to 2 previous errors
```

**Comment by tmccombs** [comment]
I wonder if it would be better to have a newtype that wraps any struct that implements `Display` like

```rust
  struct StringLike<T: Display>(T);
  
  impl<T: Display> Serialize for StringLike<T> {
    def serialize(&self, _record: &Record, _key: &'static str, serializer: &mut Serializer) -> Result<(), Error>                    {
      serializer.emit_arguments(format_args!("{}", self))
    }
  } 
```

But probably with a better name

**Comment by dpc** [comment]
I wish Rust had trait specialization already, then I could just `impl<T : Display> Serialize for T` and have more specialized implementations for first-class types. https://github.com/rust-lang/rust/issues/31844

I'll think about including a newtype like that. One can always add it to it's own crate - it's not that much code.

I also wonder, since every `k => v` is interpreted by a macro, maybe I could wrap it in something invisible that would work like default trait implementation.

Any ideas are welcome. :)

**Comment by jxson** [comment]
I'm interested in something like this as well. I loved using Bunyan in some old Node projects, and it would be really nice to be able to do something like:

    info!(log, "hello"; "mystruct" => mystruct);

Without too much fanfare. I have been playing with Serde and am wondering if there might be a simple way to to get the right behavior with any types that use the Serialize trait.

PS: I'm a Rust noob, so I might be barking up the wrong tree here...

**Comment by dpc** [comment]
@jxson You can do it for `mystruct` already. That's a solved problem. In slogv2 you can just implement https://docs.rs/slog/2.0.0-2.0/slog/trait.Value.html for `MyStruct` and call eg `emit_arguments` on `Serializer` passed to it.

The issue is opened for a type that is provided by `std`, which you can't implement traits for directly, and have to use a newtype.

**Comment by jxson** [comment]
@dpc oh nice! Feel free to remove my comments.

**Comment by dpc** [comment]
The solution for this issue comes in 2.0.0-3.1 . Basically any value that implements `fmt::Display` can be prefixed with `%` to use `fmt::Display` implementation. https://docs.rs/slog/2.0.0-3.1/slog/macro.log.html#values-implementing-fmtdisplay

Feedback is appreciated.

**Comment by dpc** [comment]
The best solution would be, https://github.com/slog-rs/slog/issues/109 but it's blocked on Rust `default impl`
