### ISSUE TITLE
Completion doesn't work for Logger and other types in intellij-rust

### ISSUE THREAD

**Issue by robinst** [slog-rs/slog#113]
I'm using [IntelliJ Rust](https://intellij-rust.github.io/) as an IDE and use slog. With IntelliJ Rust, completion usually works nicely for crates that I'm using.

The problem is that with slog, it doesn't work at all, e.g. for `Logger`. I can jump to the type using Navigate > Class..., and it will find it in the `_logger.rs` file of slog. But completion doesn't work and neither does jumping to the definition from a usage of `Logger`.

I'm pretty sure the reason for that is the use of the `include!` macro to include `_logger.rs` and co from `lib.rs`. I don't know if racer has the same problem.

Have you considered using normal `mod logger` and `pub use logger::{a, b}`? I know it's more to type, but maybe it's worth it to make completion work? It also has the advantage of making the whole API surface visible in one file.

I can also file an issue with IntelliJ Rust, but I wanted to file it here first because this is the only crates that I've encountered that uses this unusual way to define its API.

**Comment by dpc** [comment]
I believe this is the reason: https://github.com/phildawes/racer/issues/693

**Comment by robinst** [comment]
IntelliJ Rust doesn't use racer. But that answers the question whether racer has the same problem.

**Comment by dpc** [comment]
I see. You might want to report it somewhere then as well.

I'm reluctant to change code organization, as it helps me work with the code, and without https://github.com/rust-lang/rfcs/blob/master/text/1422-pub-restricted.md it leads to situations that are just very hard to express.

If I could change one thing in Rust, I'd make the modules/packages operate on directories, so that all files side by side, in one directory are one module. But oh well, that ship has sailed, I guess.

**Comment by dpc** [comment]
I'll think about it though - maybe I could workaround this, as`include!()` has clearly no first-class support everywhere.

**Comment by tmccombs** [comment]
What is the motivation for using include!() rather than using modules and publicly exporting symbols?

**Comment by dpc** [comment]
To be honest, ATM, it's that it is easier. There were cases before in other projects where  I had to do cherry-picking and tricks to have stuff public where I want it to be, yet private otherwise. Then I discovered `include` and I was thinking: it's a guilt-free solution. Only recently I figured out that `racer` doesn't jump to symbols from include files. Right now in slog, I think I could do with just modules + public reexports. I still think it's a hasle and inconvenience, but then ... I like jumping to stuff using racer as the next guy...

Ok. I'll fix it. Promise. :)

**Comment by dpc** [comment]
I have a public type, with private method. If move it to module, and want to use the private method from another sub-module - it's impossible without `pub(restricted)`. Either I make the method public (and then crate users can see what I don't want them to see). I can workaround with `#[doc(hidden)]` but it's just a pain - I have make stuff public just to make the compiler happy.

**Comment by robinst** [comment]
Would it be possible to put this method on a trait that the type implements, and use it via the trait in the other module? And then don't expose the trait in the API.

**Comment by dpc** [comment]
I don't want to compromise on the code for the sake of tooling. After all I've settled on merging everything into one big file with vim folds.

**Comment by dpc** [comment]
This should be fixed in all crates released for slog v2 (alpha versions), and I will restrain myself from using `include!` in the future.

**Comment by robinst** [comment]
Thanks! And hopefully the `pub(restricted)` story will be worked out soon.

**Comment by dpc** [comment]
> If I could change one thing in Rust, I'd make the modules/packages operate on directories, so that all files side by side, in one directory are one module

I actually take it back. I recently started working with scala, and turns out what I wanted have a different issue: leftover files of any kind are considered to be part of the module (implicitly) and may generate build errors. So build system and developer needs to be very careful to clean up everything.

**Comment by robinst** [comment]
Yeah, everything is a trade-off. Have you seen this thread? https://internals.rust-lang.org/t/lang-team-minutes-the-module-system-and-inverting-the-meaning-of-public/4804

Looks like making modules implicit is being considered.

**Comment by dpc** [comment]
@robinst I haven't. Thank you.
