### ISSUE TITLE
Example for file log

### ISSUE THREAD

**Issue by sbant** [slog-rs/slog#128]
Since slog-stream is obsoleted, what is the best way to log to file now, I can't find example in slog and slog-term.

**Comment by dpc** [comment]
`slog-term`'s `PlainSyncDecorator` takes now anything implementing `io::Write`: https://docs.rs/slog-term/2.0.0-4.0/slog_term/struct.PlainSyncDecorator.html#method.new . Just give it  an open `File`, like i https://github.com/slog-rs/term/blob/master/examples/full.rs#L11 .

Similiarily `slog-json` takes a `W : io::Write` https://docs.rs/slog-json/2.0.0-alpha2/slog_json/struct.Json.html#method.new . Similar convention is envisioned for any other crates.

**Comment by tmccombs** [comment]
Maybe `slog-term` isn't the most appropriate name anymore if it is intended to be used with non-terminal outputs.

**Comment by dpc** [comment]
Well, the output format is meant for terminals, and accidently looks OK in a file, so `slog-term` is temporarily covering that base. Ideally, I think someone should come up with a slog crate that is truly targeting logging to a file uses case:

* pick format that is best for it
* doesn't pull in irrelevant dependencies (eg. detecting color)

Potentially taking care of other features like:

* file naming
* file rotation

That would be a good `slog-file` crate. :)

I have spent most of my time figuring out the core details to make `slog` fast, versatile and robust, providing some basics. The idea is that one person can't write all possible logging features, so it's better to let community cooperate when writing their own.

Anyone interested? If not I might get to it at some point too.

**Comment by azriel91** [comment]
I'm not sure if I'm in the minority, but I do like an option to keep the ansi colour codes in my log file, and I just `less -R` those logs to view them in colour (and for sublime there's an ansi view plugin)

**Comment by dpc** [comment]
@azriel91 This one is a tricky feature. `slog_term::TermDecorator` uses `term` crate underneath that does not support it.

What could we do:
One way is: you can just write your own `slog_term::Decorator` implementation, that would wrap `io : io::Write` and output escape codes.

Another way would be to add a code to `slog-term`:

```
struct VT100Term<W>(io : W)

impl term::Terminal for VT100Term {

}
```
`term::Terminal` comes from:  https://docs.rs/term/0.4.5/term/trait.Terminal.html

and then `slog_term::TermDecoratorBuilder` could get a new method that would accept and make it use, custom `term::Terminal` type.

I would be happy to merge the later into `slog-term` if you can submit a PR. Otherwise, it will have to wait until I find some time to do it.`
