### ISSUE TITLE
Is it possible to use serder's Serializer infrastructure instead of own implemented Serializer

### ISSUE THREAD

**Issue by Xudong-Huang** [slog-rs/slog#143]
and this would control the log output format more precisely according to different logging format
e.g. in json format which allow more general analysis of log
```json
{"msg": "hello world", "key": 100}
```
instead of
```json
{"msg": "hello world", "key": "100"}
```
or even allow nested json value in the log (current we can use a string but with a lot of escape slashes)
```json
{"msg": "hello world", "key": {"a": 100, "b": true}}
```
instead of
```json
{"msg": "hello world", "key": "{\"a\": 100, \"b\": true}"}
```
better support the following control format
```rust
let logger =  slog_scope::logger().new(o!("key" => JsonValue(data))); // if data impl serde::Serialize
let logger =  slog_scope::logger().new(o!("key" => DebugValue(data))); // if data impl Debug
let logger =  slog_scope::logger().new(o!("key" => DisplayValue(data))); // if data impl Display
```

**Comment by dpc** [comment]
Quick reply, so sorry if I did not understood something.

`slog-json` does use `serde` underneath, and so can any other slog serializer. `slog-json` should be doing `{"msg": "hello world", "key": 100}` already. If not, it's a bug.

Nested values in json, have been proposed many times before. They complicate things and I have no resources to even attempt to try to support them. If you search through github issues, you will find paste discussions about it. My favourite workaround is to use a prefix model. Key named `foo.bar` would correspond to value of `bar` inside `foo`, and your custom drain, knowing the desired schema of your logging output, can output maps, lists, etc as desired, without too much overhead. You will however have to implement it yourself.

The `JsonValue`, `DebugValue` don't seem to fit the slog logging model. It's not log statements and loggers responsibility to dictate formatting to the `Drains`. Otherwise drains wouldn't be interchangable, and so on.

**Comment by dpc** [comment]
Also, note that slog does support `Debug` and `Display`: https://docs.rs/slog/2.0.6/slog/macro.log.html#fmtdisplay-and-fmtdebug-values

**Comment by Xudong-Huang** [comment]
o, I didn't notice the special macro usage. `JsonValue` is a miss leading name, I really mean `SerializeValue` which tells the drain the value impl `serde::Serialize` and the drain can still control it's format in any type of representations.

yes, slog-json already output ```{"msg": "hello world", "key": 100}```, false alarm.

I just notice that  slog's `Value/Serialize` has the same pattern as serde's `Serialize/Serializer`. maybe I'm missing something.

**Comment by dpc** [comment]
`slog::Serializer` is a spin of of a subset of `serder::se::Serializer`, yes.
