### ISSUE TITLE
Support nesting KVList and KVList manipulation in Drain's

### ISSUE THREAD

**Issue by bbangert** [slog-rs/slog#151]
I would like to manipulate the record's KV arguments before using the JSON Drain. Right now this is impossible, because to create a new OwnedKVList, one must have internal access to the existing OwnedKVList to pass its node to OwnedKVList::new. There should be some way externally to create a new OwnedKVList so that key/values can be added to an existing one (ie, from in a Drain).

Additionally, before printing the output in the JSON drain, I'd like to move all of the records kv arguments to a nested structure. slog's OwnedKVList does not seem to support nesting a OwnedKVList as a Value in a OwnedKVList. That is, I want my final output to have the records msg as 'message', with its siblings as the records kv arguments, while the logger's kv arguments are in the main structure.

ie:
```
{..Logger KV args.. "Fields": {"message": (Record.msg()).. Record KV args} }
```

This is needed due to how our operations team handles JSON logging output, and right now the only way I'm able to get close is to completely fork slog-json to manipulate the serialization output.

If OwnedKVList and the Record could be manipulated from a Drain, I'd be able to just make a small Drain that does the desired manipulation and compose it with the existing slog-json.

**Comment by dpc** [comment]
I don't think I've understood the first part. Maybe you're looking for https://github.com/slog-rs/slog/blob/effa98bc85a08d82e27ac5ed8cd5d172a50b8642/src/lib.rs#L1195 ? Basically, you should never really have a need to create `OwnedKVList`s. Just create your own structs that implement a `KV` and this way you can control what and how they are outputting it with a code snippet. You can't modify the data directly because it's immutable and thread-safe, but you can do any operations your desire on it.

The nested structs is a common request. If you search the past issues you will find previous discussions about it.

Forking `slog-json` is a very reasonable idea. Slog was created with the idea of allowing substituting all the pieces with own implementation. The license is permissible, and the source should be tiny and reasonably easy to hack in whatever scheme you'd like to use. You could eg. use special tags/types/values to mean "nesting start/end", or if you know the schema beforehand and have only handful types to support it, you could just match the key directly, etc.

**Comment by dpc** [comment]
Nesting is now suported (behind a feature flag, until next major release).
