### ISSUE TITLE
Minimum rust version bump in minor version release is a breaking change

### ISSUE THREAD

**Issue by Dylan-DPC** [slog-rs/slog#188]
This [commit](https://github.com/slog-rs/slog/commit/77e6f0100497270e6f8ce3fe9e0631ad073f8c2f) bumps the minimum version from 1.15.0 to 1.26.1 which is a breaking change and it breaks [builds](https://travis-ci.org/uuid-rs/uuid/jobs/434905483#L1023)  for us which depend on 1.22.0 rust version. 

One solution i to wrap the u128 support in an optional feature gate.

**Comment by ubnt-intrepid** [comment]
@Dylan-DPC Thanks for reporting the issue.
I've created the patch fixed around those problems and we'll soon release a patched version.

**Comment by Dylan-DPC** [comment]
@ubnt-intrepid thanks for the quick reply. :+1:

**Comment by dpc** [comment]
@Dylan-DPC 

I find the whole situation in Rust ecosystem intolerable. On one hand the language is rapidly improving, on the other maintainers of libraries like this one have to go out of their way to support both users that require new language features support and users of old compilers.

If cargo learned to use rustc version as a dependency version than the whole problem would not be happening, and users on old compiler versions would just keep using older versions of crates that require a newer compiler. Everyone would be happy.



Personally, I am against adding a feature flag in this case and will definitely not do it myself and would just say to affected users: run `rustup update` please - 1.26 is old enough. 

But if @ubnt-intrepid wants to take a lead on it it's fine with me and big kudos.

**Comment by ubnt-intrepid** [comment]
@dpc I agree that it is painful to develop with considering both of old and new Rust versions.

IMO, since the library is versioned with semver, as long as there is an influence, adding new features related to the new language features should be as cautious as possible. Making the added feature gate the default (or remove it assuming it is always enabled) should be done when the version bumps up to 3.0 (at the same time we could increase the minimal Rust version).

**Comment by dpc** [comment]
Bumping the major version creates an avalanche, where every other slog crate has to bump major version, which creates churn and confusion. Users are getting errors like `X does not impl slog::Drain` even though it does - the problem is that it's a `slog::Drain` in a different version. It's super confusing, and any unrelated dependency can pull a different version of `slog` in, and things stop compiling. Some of the other crates are 3rd party and they might never get updated. It's a painful experience, and after v1 to v2 migration, I would advise avoiding v2 to v3 for as long as possible. There are some tricks to make v(X) and v(X+1) backward comp. but they are a log of boilerplate work, from what I can tell.

I don't consider rustc version to be part of semver guarantees. Some people might, but I don't. It's arbitrary distinction. The API didn't change. It's just a compiler that is too old, which is different. For me the minimum rustc guarantee is just "be a good sport" agreement that everyone should have enough time to upgrade their compiler version, and not everyone can `rustup update` in their crontab.

Also, I'd like to point out, that project that don't want to "get broken" should just use `Cargo.lock` not hit the `cargo update` button without being ready to hit the `rustup update` button as well. Whoever is not ready.

Anyway, I admit that I'm just a bit bitter because I have very little time nowadays, and problems like that annoy me a lot, because I would like the world to be a happy place, and all slog users to dance cheerfully, without me having to continosly do unnecessary (IMO) work.


We just badly need this: https://github.com/rust-lang/rfcs/pull/2495

**Comment by Dylan-DPC** [comment]
@dpc 

I agree with the thought of pushing minimum rust version as close to stable as possible but then as authors of libraries which are used in many other libraries it often becomes a painpoint - as every version  has to push a new major release which is difficult for crates that are already in post 1.0 phase. 

It's always a case with breaking changes where things get subjective and I prefer playing the defensive card and reserving them for the major changes. Also worth noting is that I have come across some few cases where people are stuck on a certan rust version for a reason. Though I dislike it and move to the latest as much as possible, and rust does a good job with compatibility between the versions, you can't help it when someone decides not to update.

Generally what we do with uuid is, anything on nightly or features implemented in the recent stable versions are under feature gates so that it keeps both parties - the ones who are stuck with old versions and the others who like to try out the latest shiny features. 

Thanks for all the work :+1:

**Comment by Techcable** [comment]
As @Dylan-DPC said, I think there is somewhat of a precedent among rust crates that increasing the minimum rust version is not a breaking change. It is something @dpc can do at any time.
However, this stable version is was released relatively recently and I think it'd be nice to put `u128` support behind a feature flag for the time being (like serde does).

bluss's [itertools crate](https://crates.io/crates/itertools) and [serde](https://crates.io/crates/serde) both seem to be willing to increase the minimum required rust version *at any time they please*. Serde has done it multiple times after 1.0, even though they have only made patch releases. These are some of the most popular crates in the rust ecosystem (7 mil downloads), so I think adopting their rust versioning policy would be perfectly normal.

Interestingly, bluss's [indexmap crate](https://crates.io/crates/indexmap) takes a much more conservative approach, guarenteeing that [the minimum supported rust version will only increase on a 1.x release](https://docs.rs/indexmap/1.0.1/indexmap/#rust-version) (although it's relatively minor in comparison to the other two crates). Although I disagree with this approach, it is an option you could consider.

**Comment by KodrAus** [comment]
Personally, my yardstick for a _good sport minimal version_ is what's available in package repositories. Right now, at least for Ubuntu, that looks like `1.25.0`, which seems kind of old to me.

I totally sympathize with @dpc's frustration at being held back by old compilers, when Rust has a rapid release cycle and tooling that makes upgrading easy. Putting that burden on library maintainers means we have complex infrastructure in our crates to maintain. Running old stuff is a net-negative, and we need a better system to manage minimum versions than the ad-hoc schemes we currently have throughout the ecosystem, which aren't very effective. Right now though that's pretty much the system we have.

Either miminum versions in `Cargo.toml`, or some reasonable, well-defined LTS boundary that's a bit longer than the 6-week stable cadance would be a great improvement.

Whatever policy `slog` wants to adopt is up to its maintainers, but one thing that is nice is to put something in the readme that clarifies what that policy is.

**Comment by Dylan-DPC** [comment]
Its fine to be aggressive with bumping the minimum version but given the current ecosystem it is better to be kept for major releases till cargo can pick minor versions based on rust versions.

**Comment by ubnt-intrepid** [comment]
> @Techcable 
> ...(omit)...
> bluss's [itertools crate](https://crates.io/crates/itertools) and [serde](https://crates.io/crates/serde) both seem to be willing to increase the minimum required rust version _at any time they please_. Serde has done it multiple times after 1.0, even though they have only made patch releases. These are some of the most popular crates in the rust ecosystem (7 mil downloads), so I think adopting their rust versioning policy would be perfectly normal.

I found that serde checks the compiler version in `build.rs` and turns off support for newer language features if the rustc version is old. In that case, the crate user don't have to responsibility to care about (additional/removal) feature flags in `Cargo.toml`.

It seems good to adopt such approach for avoiding changes on the surface.

**Comment by Dylan-DPC** [comment]
> It seems good to adopt such approach for avoiding changes on the surface.

True but might be tedious to maintain. 

Instead I would suggest don't change the minimum version on minor releases, anything that requires features from recent releases should be in a feature gate and then when you do a major version release, bump the minimum version aggressively. It might be difficult for 1.0+ crates.

**Comment by CAD97** [comment]
@Dylan-DPC 

I'd like to clarify something here.

There's no good option for crates used as _public dependencies_.

For a crate like slog, num-traits, or serde, part of the point of being used is that they're (often) public dependencies of crates that depend on them. This introduces massive strain on any crate that has it as a public dependency (see: libc-pocalypse) when the crate publishes a breaking update.

This can be avoided by the semver trick. But if the breaking change is a newer compiler version, this means that you can't do the semver trick, as that would require the new compiler version!

Breaking changes are _prohibitively_ expensive for crates used as public dependencies throughout the ecosystem. So if compiler updates are going to be taken advantage of, either the minimum compiler version needs to go up, and your users just need to use rustup-update, or you're stuck maintaining conditional shimming.

**Comment by Dylan-DPC** [comment]
@CAD97 yes I understand. Right now it is a tradeoff between supporting a large number of projects or using the latest features with features gates, build scripts, etc acting as ways to maintain equilibrium between both. I generally prefer to stick to newer features, but in some cases you don't have an option.
