### ISSUE TITLE
Field output order reversed?

### ISSUE THREAD

**Issue by U007D** [slog-rs/slog#213]
The following:
```rust
pub enum Event {
    Timestamp,
    Hello(u32),
    LogSchemaVersion,
}

impl Event {
    pub fn key(&self) -> &'static str {
        match self {
            Event::Timestamp => ...
        }
    }
}

impl KV for Event {
    fn serialize<'a>(&self, record: &Record<'a>, serializer: &mut dyn Serializer) -> SlogResult {
        serializer.emit_str(
            self.key(),
            &match self {
                Event::Timestamp => Utc::now().to_rfc3339...
            },
        )
    }
}
...
let logger = slog::Logger::root(drain, o!(Event::LogSchemaVersion, Event::Timestamp));
info!(logger, ""; Event::Hello(64));
```
outputs:
```plain
Jun 29 14:38:40.457 INFO hello: 64-bit_world!, timestamp: 2019-06-29T21:38:40.458542000Z, log_schema_version: 0.0.1
```
I'm working on the double-timestamp issue, but my question is **why did my fields come out in the reverse order I specified them?**  `log_schema_version` really should be first so that parsers know how to parse the rest of the log record.
Is there a control for this that I've missed somewhere?

**Comment by dpc** [comment]
In `slog` the list is being maintained

`a` <- `b` <- `c` <- `d` <- Logger holds the reference to last element. Because of this semantics of owned values, I decided that even imediate (borrowed) arguments are added in reverse. This is so that.

```
let log = Logger::root(o!(a));
let log = log.new(o!(b));
let log = log.new(o!(d));
let log = log.new(o!(d));
let log = log.new(o!(e));
let log = log.new(o!(f));
info!(log, g);
```

is the same as

```
let log = Logger::root(o!(a, b));
let log = log.new(o!(c, d));
info!(log, e, f , g);
```

If you really need it any other way, it shouldn't be too difficult to just write a macro that looks like original `info!` etc. but reverses them.

It's also possible to write a drain implementation that outputs them in reversed order, but that will have to do buffering, so will be a bit slower (that's why it's not the default).

**Comment by U007D** [comment]
I see.  Thank you for the explanation!
