### ISSUE TITLE
Possible to add another drain to an existing root logger?

### ISSUE THREAD

**Issue by SohMahmood** [slog-rs/slog#306]
Apologies if this is a basic question but I did not find something in the docs for this.

Let's say you built the root logger in the beginning of your program and then you needed to add a new file drain to the root logger if a certain condition is met in the middle of your program, would that be doable?

**Comment by dpc** [comment]
You can either use the existing `Logger` as a `Drain` for a new `Logger` that will replace the old one (because of https://docs.rs/slog/latest/slog/trait.Drain.html#impl-Drain-2), or you can implement your own `struct MyMagicDrain` that `impl Drain for MyMagicDrain` and inside do some magic to conditionally log to different places. There's also https://docs.rs/slog-atomic/
