### ISSUE TITLE
logging json objects (especially in the json logger)

### ISSUE THREAD

**Issue by dimbleby** [slog-rs/slog#77]
Suppose eg I've queried some REST API and gotten and parsed JSON response.  So now I have some object that I know how to JSON-serialise.

I'd love to be able to log that object, retaining it's JSON-ness:

``` json
{"ts":"2016-10-21T09:08:08.121850169+01:00","level":"INFO","response": {"ip":"1.2.3.4"}}
```

But so far as I can see, the best that I can do is to do my own serialization and log the resulting string, with output something like this:

``` json
{"ts":"2016-10-21T09:08:08.121850169+01:00","level":"INFO","response":"{\"ip\":\"192.91.191.29\"}"}
```

which has lost - or at least made it harder to recover - the structure.

Is what I'm looking for already possible?  If not, is there any chance of an enhancement allowing it?

Thanks!

**Comment by dpc** [comment]
No easy general solution is currently available for your interesting use case. But there are some possiblities still.

The easiest I can thing of is deserializing the response, and just making a child `Logger` with it's values (if you happen to know them beforehand).

There is a solution that requires some custom-effort. As all `Drain` parts are custom and you can replace them with your own stuff, You could write your own `Format` that you would use instead of `slog_json::Format`. That format would know (either by key-name, or something about the value), which fields are already encoded Json, and would output them specially: as a sub-map value or something like that. You could even introduce own `struct` implementing `Serialize` to make it more generic. If done right it could be even incorporated into `slog-json` crate or it's own generic crate.

I was thinking about a possibility of introducing structured/sequence data type, so serializers can output fields that are vecs, dicts and so on, but it's hard to do as a generic feature, and I'm short on time.

Feel free to discuss on gitter on here, maybe we can cook something up. But you/someone would have to lead the future development, as I'm busy with other things (but I can help!).

**Comment by dimbleby** [comment]
Thanks for your thoughts.

Since raising this I've figured out how to make [fluentd](http://www.fluentd.org/) handle the stringified logs that I'm currently getting.  I view this as something of a workaround (I'd still prefer to log JSON directly, rather than log a string and then have to parse it) - but it's a workaround that is going to be good enough.

Therefore I'm probably not going to be sufficiently motivated to drive making code changes here.

So from my point of view please feel free either to: 
- keep this open (eg if you think it's a good idea, and having an open issue is a helpful way of tracking that this is on the wishlist, and maybe one day you or some other contributor will get around to it)
- or close it (eg if you prefer to use issues to track things that you actually intend to address)

**Comment by dpc** [comment]
I'm going to keep this for visibility. Thanks for taking time to describe it, and I'd happy to hear in the future how did slog work out for your application. :)

**Comment by dpc** [comment]
Closing for now. It seems to me it's requirement custom enough to leave for people that need it to come up with a right solution - probably something similar to what I described in previous comments.

**Comment by dpc** [comment]
itshappening.gif

Check out `serde` branch, which might soon get merged into master.

**Comment by dimbleby** [comment]
Cool!  thanks for remembering this issue and letting me know.
