### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by valarauca** [slog-rs/slog#83]
Several wiki pages links and the crates.io Documentation link now points to 404'd links. I was attempting to give slog a whirl last weekend and this ended up being a big source of frustration for me. 

Also if there could be a simple example for getting started with  `journald` and `flat file` logging? Just reading the docs it isn't very apparent how these separate crates integrate.

**Comment by dpc** [comment]
Hi. Sorry for the trouble. Slog went from being under my github account into a github community.

If you can point out links that are wrong, that would be helpful. Otherwise I'm fixing them as I spot them.

https://github.com/slog-rs/misc/blob/master/examples/global_file_logger.rs might be helpful for logging to a file. 

Journald is very fresh crate, and I don't think it was even published yet. I think it comes down to putting 

https://github.com/slog-rs/journald/blob/master/src/lib.rs#L41

in your drain tree, link in the example: https://github.com/slog-rs/journald/blob/master/src/lib.rs#L15

@tmccombs BTW. Should we publish `slog-journald` ?

**Comment by tmccombs** [comment]
I just published slog-journald.

Also, one place with a broken link is the Documentation link on crates.io. The documentation link in Cargo.toml should probably be fixed.

**Comment by dpc** [comment]
Cargo.toml documentation link is fixed in git, so will update during next release.

Closing for now. Feel free to reopen and/or continue the discussion here.
